/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @create date 2026-08-28
 * @modify date 2026-08-28
 * @desc Correlation, policy, cancellation, and deadline metadata carried by every host operation.
 */

export type AiCoderTaskMode =
  | "auto"
  | "scaffold"
  | "refactor"
  | "review_only"
  | "validate_only";

/**
 * Context shared by all operations in one run. `deadline` is an absolute Unix
 * timestamp in milliseconds so adapters cannot accidentally reset the budget.
 */
export type RunExecutionContext = Readonly<{
  deadline: number;
  mode: AiCoderTaskMode;
  runId: string;
  signal: AbortSignal;
  taskId: string;
  workspaceRoot: string;
}>;

/**
 * Context for one routed tool call. The idempotency key is generated by the
 * core, never by the model, and remains stable across safe retries.
 */
export type ToolExecutionContext = RunExecutionContext &
  Readonly<{
    idempotencyKey: string;
    toolCallId: string;
  }>;

export function isExecutionCanceled(
  context: RunExecutionContext,
  now = Date.now(),
): boolean {
  return context.signal.aborted || now >= context.deadline;
}
